pipeline:
# Build the drupal 7 module
    build-d7-vmod:
        image: ubuntu
        commands:
            - apt update; apt -y install curl
            - apt -y install libvarnishapi-dev libvarnishapi1 varnish libtool automake python-docutils pkg-config
            - cd libvmod-drupal7; mkdir install; ./autogen.sh; ./configure --prefix=$PWD/install; make -j; make install
            - find . 
# Build and push release
    build-and-push-branch:
        image: plugins/docker
        repo: fpfis/varnish
        tags: 5.2 
        secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
        when:
            event: push
