pipeline:
# Build the drupal 7 module
    build-d7-vmod:
        image: ubuntu
        commands:
            - apt update; apt -y install curl
            - curl -s https://packagecloud.io/install/repositories/varnishcache/varnish61/script.deb.sh | bash
            - apt -y install varnish-dev libtool automake python-docutils
            - cd vmod-drupal7; mkdir install; ./autogen.sh; ./configure --prefix=$PWD/install; make -j; make install; cd ..
            - cd varnish-modules; ./bootstrap; ./configure; make -j
            - find . 
# Build and push release
    build-and-push-branch:
        image: plugins/docker
        repo: fpfis/varnish
        tags: 6.1 
        secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
        when:
            event: push
